version: '3'
services:
  heyamikoo:
    build:
      context: .
      dockerfile: Dockerfile.heyamikoo
    container_name: heyamikoo
    privileged: true
    network_mode: host
    ports:
      - 1883:1883
    restart: on-failure
    depends_on: 
      - rhasspy
  rhasspy:
    image: "rhasspy/rhasspy"
    container_name: rhasspy
    restart: unless-stopped
    volumes:
        - "./rhasspy/profiles:/profiles"
        - "/etc/localtime:/etc/localtime:ro"
    ports:
        - "12101:12101"
    devices:
        - "/dev/snd:/dev/snd"
    command: --user-profiles /profiles --profile es